package com.example.ch.mapper;

import com.example.ch.model.Comments;
import com.example.ch.model.CommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:08 JST 2024
     */
    long countByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int deleteByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    List<Comments> selectByExample(CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    Comments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int updateByExampleSelective(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int updateByExample(@Param("record") Comments record, @Param("example") CommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Mon Sep 30 21:52:09 JST 2024
     */
    int updateByPrimaryKey(Comments record);
}