package com.example.ch.model;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.comment_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    private String commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.content
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.user_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.post_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.created_at
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.comment_id
     *
     * @return the value of public.comments.comment_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.comment_id
     *
     * @param commentId the value for public.comments.comment_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.content
     *
     * @return the value of public.comments.content
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.content
     *
     * @param content the value for public.comments.content
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.user_id
     *
     * @return the value of public.comments.user_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.user_id
     *
     * @param userId the value for public.comments.user_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.post_id
     *
     * @return the value of public.comments.post_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.post_id
     *
     * @param postId the value for public.comments.post_id
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public void setPostId(String postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.created_at
     *
     * @return the value of public.comments.created_at
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.created_at
     *
     * @param createdAt the value for public.comments.created_at
     *
     * @mbg.generated Fri Oct 18 22:59:48 JST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}