package com.example.ch.model;

import java.util.Date;

public class Posts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.post_id
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.title
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.content
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.user_id
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.posts.update_at
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.post_id
     *
     * @return the value of public.posts.post_id
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.post_id
     *
     * @param postId the value for public.posts.post_id
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.title
     *
     * @return the value of public.posts.title
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.title
     *
     * @param title the value for public.posts.title
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.content
     *
     * @return the value of public.posts.content
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.content
     *
     * @param content the value for public.posts.content
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.user_id
     *
     * @return the value of public.posts.user_id
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.user_id
     *
     * @param userId the value for public.posts.user_id
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.posts.update_at
     *
     * @return the value of public.posts.update_at
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.posts.update_at
     *
     * @param updateAt the value for public.posts.update_at
     *
     * @mbg.generated Tue Jun 04 01:23:34 JST 2024
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}