package com.example.ch.model;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.user_id
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.user_name
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password_hash
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.email
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.update_at
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.user_id
     *
     * @return the value of public.users.user_id
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.user_id
     *
     * @param userId the value for public.users.user_id
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.user_name
     *
     * @return the value of public.users.user_name
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.user_name
     *
     * @param userName the value for public.users.user_name
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password_hash
     *
     * @return the value of public.users.password_hash
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password_hash
     *
     * @param passwordHash the value for public.users.password_hash
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.email
     *
     * @return the value of public.users.email
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.email
     *
     * @param email the value for public.users.email
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.update_at
     *
     * @return the value of public.users.update_at
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.update_at
     *
     * @param updateAt the value for public.users.update_at
     *
     * @mbg.generated Tue Jun 04 01:23:00 JST 2024
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}