package com.example.ch.model;

public class UsersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbg.generated Sat May 18 12:43:30 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.user_id
     *
     * @mbg.generated Sat May 18 12:43:30 JST 2024
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.id
     *
     * @return the value of public.users.id
     *
     * @mbg.generated Sat May 18 12:43:30 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.id
     *
     * @param id the value for public.users.id
     *
     * @mbg.generated Sat May 18 12:43:30 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.user_id
     *
     * @return the value of public.users.user_id
     *
     * @mbg.generated Sat May 18 12:43:30 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.user_id
     *
     * @param userId the value for public.users.user_id
     *
     * @mbg.generated Sat May 18 12:43:30 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}